name: ci-py-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: $ {{matrix.python}}
      - run: python ./Project/test.py